#Site settings
baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://thathanka.org/" # the base hostname & protocol for your site

# Site metadata
title: Travis Rasor
tag_text: Travis Rasor
description: Travis Rasor


# Build settings
markdown: kramdown
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "serve_development.sh"
  - "build.log"
sass:
  style: compressed

gems:
  - jekyll-seo-tag

twitter:
  username: tlrasor